### ISSUE TITLE
添加选择显示器功能

### ISSUE THREAD

**Issue by 4-0-4-notfound** [SDchao/Time2Rest#5]
在双屏使用时分辨率不正确

**Comment by SDchao** [comment]
感谢反馈，能否提供下你的显示屏信息与分辨率？

软件应当显示在主显示器，以主显示器分辨率为主。
我的测试环境是主显示器2560*1440，副显示器1920*1080，一切正常

**Comment by 4-0-4-notfound** [comment]
两个都是1080p，但是缩放率不一样，一个100%，一个150%

**Comment by SDchao** [comment]
尝试更改缩放率仍然无法复现……
请问可以上传一下程序的截图吗？

**Comment by 4-0-4-notfound** [comment]
![image](https://user-images.githubusercontent.com/76674846/132628644-c3af4e07-d408-49b3-9a9e-1a0324ce10c8.png)

在副屏上显示

**Comment by SDchao** [comment]
感谢提供截图，请问在只有一个显示器的情况下是否还会有问题？
程序需要退出重开才会更改分辨率。如果您有空尝试的话，记得先退程序再改显示器设置

**Comment by 4-0-4-notfound** [comment]
单个显示器没问题，程序关了重开之后就没这个问题了（双显示器也ok了）  

期望能加入显示在哪个显示器上的功能

**Comment by SDchao** [comment]
感谢反馈！我修改一下标题以作记录。

**Comment by SDchao** [comment]
功能已于 7110e6c27d442fa9c74ce633eb9308e973ff22cb 添加
