### ISSUE TITLE
有个严重的问题

### ISSUE THREAD

**Issue by yuzhen1024** [SDchao/Time2Rest#7]
有个严重的问题，当打开这个软件之后，桌面的所有快捷键都会失效。
「桌面图标->右击->属性->快捷键」的功能。
![批注 2021-10-09 055725](https://user-images.githubusercontent.com/47154428/136629343-3cd94e7e-9136-41f2-b22e-0411257ef5f2.jpg)

**Comment by SDchao** [comment]
目前我的系统快捷键功能一直是失效的……所以没有办法复现

**Comment by yuzhen1024** [comment]
问题来源：https://github.com/SDchao/Time2Rest/blob/ad3b0391db4bb5b87637837d94a1f0102302c305/Time2Rest/AlertForm.cs#L186-L190
一个特征是，注释掉186,187或189,190能解决问题，但问题的原因未知。

**Comment by SDchao** [comment]
猜测是微软发现有全屏应用就会禁用桌面快捷键。暂时可能没有较好的解决方案。

**Comment by yuzhen1024** [comment]
> 问题来源：
> 
> https://github.com/SDchao/Time2Rest/blob/ad3b0391db4bb5b87637837d94a1f0102302c305/Time2Rest/AlertForm.cs#L186-L190
> 
> 
> 一个特征是，注释掉186,187或189,190能解决问题，但问题的原因未知。

该判断不准确，问题完全无厘头。
关闭issue。
